### ISSUE TITLE
g++ 12 does not support extended character

### ISSUE THREAD

**Issue by dj-zhou** [Neargye/magic_enum#235]
I am compiling magic_enum v0.8.2 on Ubuntu 22.10 on which I have 12.2.0 of g++:
```
$ g++ --version
g++ (Ubuntu 12.2.0-3ubuntu1) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
However, I got many errors like:
```
/home/robot/soft/magic_enum/test/test.cpp:54:69: error: extended character 😃 is not valid in an identifier
   54 | enum class Language : int { 日本語 = 10, 한국어 = 20, English = 30, 😃 = 40 };
      |                                                                     ^
/home/robot/soft/magic_enum/test/test.cpp:140:60: error: extended character 😃 is not valid in an identifier
  140 |     REQUIRE(enum_cast<Language>("😃").value() == Language::😃);
      |                                                            ^
/home/robot/soft/magic_enum/test/test.cpp:194:58: error: extended character 😃 is not valid in an identifier
  194 |     REQUIRE(enum_cast<Language>(40).value() == Language::😃);
```

**Comment by Neargye** [comment]
By default extended character is off by settings `MAGIC_ENUM_OPT_ENABLE_NONASCII`.  Could you show an example of building a library?

**Comment by joseviccruz** [comment]
Same here, it happens with `MAGIC_ENUM_OPT_ENABLE_NONASCII OFF` as well.

Example building using `CMake`.
```bash
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX="/opt/magic_enum"
make
```

The same steps above worked on g++ 11.3.0 Ubuntu 22.10

**Comment by dreirund** [comment]
`-DMAGIC_ENUM_OPT_BUILD_TESTS=ON` also influences this, see #244.

**Comment by dj-zhou-bg** [comment]
> By default extended character is off by settings `MAGIC_ENUM_OPT_ENABLE_NONASCII`. Could you show an example of building a library?

Just like this:
```
     git clone https://github.com/Neargye/magic_enum.git
     cd magic_enum
     mkdir build
     cd build
     cmake ..
     make -j4
     sudo make install
```
My system is Ubuntu 22.04, the default g++ version is of 12.x.y. 
There is no problem on Ubuntu 20.04, since the default g++ version is 11.3.x.
