### ISSUE TITLE
magic_enum.hpp:268:47: fatal error: instantiating fold expression with 257 arguments exceeded expression nesting limit of 256   constexpr int count = ((valid[I] ? 1 : 0) + ...);

### ISSUE THREAD

**Issue by bsergean** [Neargye/magic_enum#102]
This is with version v0.6.6. Does this ring a bell to anyone ?

```
  constexpr int count = ((valid[I] ? 1 : 0) + ...);
```

In our version the method where compilation error happens looks like this:

```
template <typename E, int... I>
constexpr auto values(std::integer_sequence<int, I...>) noexcept {
  static_assert(is_enum_v<E>, "magic_enum::detail::values requires enum type.");
  constexpr std::array<bool, sizeof...(I)> valid{{is_valid<E, I + reflected_min_v<E>>()...}};
  constexpr int count = ((valid[I] ? 1 : 0) + ...);

  std::array<E, count> values{};
  for (int i = 0, v = 0; v < count; ++i) {
    if (valid[i]) {
      values[v++] = static_cast<E>(i + reflected_min_v<E>);
    }
  }

  return values;
}
```

**Comment by Neargye** [comment]
Look same https://github.com/Neargye/magic_enum/issues/69

**Comment by bsergean** [comment]
Yes this is working well in 0.7.3, will close this.
