### ISSUE TITLE
static assertion failed with gcc 9.2.1

### ISSUE THREAD

**Issue by morph208** [Neargye/magic_enum#28]
Hello,

We have been trying to use magic_enum::enum_count. It works well with Visual Studio 2017 but does not compile with gcc 9.2.1. Here is the code:

```
enum class MyEnum : std::size_t
{
    Value0,
    Value1,
    Value2
};
constexpr std::size_t countEnum = magic_enum::enum_count<MyEnum>();
```

And with gcc 9.2.1 we have the following issue: 

> MagicEnum.h:442:26: error: static assertion failed: magic_enum::enum_range requires enum implementation and valid max and min.
> static_assert( count > 0, "magic_enum::enum_range requires enum implementation and valid max and min." );

We have the latest version of MagicEnum as of today. We have looked at the limitations, we don't seem to be in one of those situations. Did we miss anything? It looks like it is supposed to work from gcc 9 and upward.

Thank you so much for your work and very nice contribution. Magic enum seems pretty cool.

Cheers,

Olivier

**Comment by Neargye** [comment]
Hi @morph208,

Example gcc9.2: https://godbolt.org/z/d3cXHr

This situation may occur if forward declared  enum: https://godbolt.org/z/h9b_SK

**Comment by morph208** [comment]
Thanks for your very quick reply. It's not forward declared but maybe I cannot use it like I do. I'm trying to get the size of the enum to declare an std::array of that size. Since the count it's constexpr I would have expected to work. I do not call it from the main like you did in your example, I should probably have told you that earlier. Sorry about that. Anyway it compiles and works as expected with VS2017. Here the complete code below:

```
#pragma once
#include "MagicEnum.h"
#include <array>

namespace myNamespace
{
enum class MyEnum  : std::size_t
{
    Value0,
    Value1,
    Value2,
};
constexpr std::size_t countEnum = magic_enum::enum_count<MyEnum>();

using MyList = std::array<bool, countEnum>;

class MyClass
{
public:
    MyClass() = default;
    ~MyClass() = default;

private:
    MyList m_myList;
};
}    // end of namespace myNamespace
```

**Comment by Neargye** [comment]
Thanks for update example, I will check it later.

**Comment by Neargye** [comment]
Hi @morph208,
Could you help to debug and run some code
```cpp
std::cout << (int)MyEnum::Value0 << magic_enum::enum_name<MyEnum::Value0>() << std::endl;
std::cout << (int)MyEnum::Value1 << magic_enum::enum_name<MyEnum::Value1>() << std::endl;
std::cout << (int)MyEnum::Value2 << magic_enum::enum_name<MyEnum::Value2>() << std::endl;
```

**Comment by morph208** [comment]
Hey @Neargye 

Sorry for the delay. I was very busy with a release. Anyway, here the output you needed:

> 0Value0
> 1Value1
> 2Value2

Obviously the output was generated on Windows with VS 2017. I cannot give you an output on gcc 9.2.1 since it does not even compile.

**Comment by morph208** [comment]
Any news on this? I haven’t heard from you since early March.

**Comment by Neargye** [comment]
Hi @morph208,
Sorry for the long answer, to be honest, I had a very busy time.
I don’t know yet where the is a problem. Could you tell the OS and the version of the compiler on which the bug is occur, I will try to play it in the virtual machine.

**Comment by morph208** [comment]
No worries, totally understandable. The OS is Linux Mint 19 and the compiler is gcc 9.2.1.

**Comment by zweistein22** [comment]
Hello, 
I have the same compile error 
"magic_enum::enum_range requires enum implementation or valid max and min."
 , but in a special snapcraft.yaml build.
Same source code as on linux ubuntu 18 same compiler gcc 9.3, everything same, but  since yesterday inside snapcraft.yaml compilation broken . I played around with LC_LOCAL and libgtk2.0-dev, but cannot reproduce yet... compilation always broken which makes me think of a recent gcc or magic-enum change.

**Comment by egorpugin** [comment]
https://github.com/Neargye/magic_enum/issues/53 looks similar to this one.
