### ISSUE TITLE
magic_enum 0.8.0 fails to compile with latest MSVC17

### ISSUE THREAD

**Issue by ghost** [Neargye/magic_enum#195]
Hey after upgrading magic enum from 0.7.3 to 0.8.0 (from Conan-center) I'm Encountering compiler errors with latest MSVC17 (at the time of writing VS 2022 17.2.5).
I

The Compile error occurs when FreeRTOS.h is included before magic_enum.hpp

```
#include <FreeRTOS.h>
#include <magic_enum.hpp>
//no more source code needed to reproduce the compile error
```

this line from magic_enum.hpp causes the error
```

  struct secondary_hash {
    constexpr std::uint32_t operator()(string_view value) const noexcept {
      auto acc = static_cast<std::uint64_t>(2166136261ULL);
      for (const auto c : value) {
        acc = ((acc ^ static_cast<std::uint64_t>(c)) * static_cast<std::uint64_t>(16777619ULL)) & std::numeric_limits<std::uint32_t>::max(); ///< Compiler error here
      }
      return static_cast<std::uint32_t>(acc);
    }
  };


```

```
C:\.conan\adf281\1\include\magic_enum.hpp(742): error C2589: "(": invalid Token on the right hand side of "::"
C:\.conan\adf281\1\include\magic_enum.hpp(742): error C3878: Syntaxfehler: unexpected Token „(“ after „expression“
```

Could you try to reproduce this issue?
thank you :)

**Comment by ghost** [comment]
I Think I found a solution.
There is a small difference between the conan center version 0.8.0 and the latest version from the master branch


Latest master Version
`acc = ((acc ^ static_cast<std::uint64_t>(c)) * static_cast<std::uint64_t>(16777619ULL)) & (std::numeric_limits<std::uint32_t>::max)();`

Conan Center 0.8.0
`
acc = ((acc ^ static_cast<std::uint64_t>(c)) * static_cast<std::uint64_t>(16777619ULL)) & std::numeric_limits<std::uint32_t>::max();
`

Note the extra () around std::numeric_limits::max. With these extra brackets compiling works fine

=> Could you tag a new version from the latest master and upload it to conan center?
I believe this will fix my issue

Thx a lot for your great work :)

**Comment by Neargye** [comment]
planned release after close all in https://github.com/Neargye/magic_enum/milestone/1
